package com.inheritance.assignment_constructors;


//default constructor parent() generated by compiler
class Parent3{
	 // default constructor parent() {empty}
}
public class Child3 {
Child3()
{
	super();   //calling parent cls con
	System.out.println("child class 0-arg constructor");
}
	public static void main(String[] args) {
new Child3();
	}

}


