package com.inheritance.assignment_instanceblock;

// first is executed instance

class Parent1{
	{
		System.out.println("parent instance block");
	}
	Parent1(){
		System.out.println("parent class 0-org cons");
	}
}
public class Child1 {

	{
		System.out.println("child instance block");
	}
	Child1()
	{ //super(); code is generated by compiler 
		System.out.println("child class 0-org cons");
	}
	public static void main(String[] args) {
new Child1();//  During object creation
} 
}