package com.inheritance.assignment_staticblock;

//first is executed static

class Parent1{
	static {
		System.out.println("parent static block");
	}
	Parent1(){
		System.out.println("parent class 0-org cons");
	}
}
public class Child1 {

	static {
		System.out.println("child static block");
	}
	Child1()
	{ //super(); code is generated by compiler 
		System.out.println("child class 0-org cons");
	}
	public static void main(String[] args) {
		new Child1();
	}
	}
 