package com.inheritance.assignment_staticblock;

// instance block is executed during object creation & static blocks are executed by class loaded
class Parent3{
	{
		System.out.println("parent3 class intance");
	}
	static {
		System.out.println("parent static block");
	}
	Parent3(){
		System.out.println("parent class 0-org cons");
	}
}
public class Child3 {
	{
		System.out.println("child3 class intance");
	}
  
	static {
		System.out.println("child static block");
	}
	Child3()
	{ //super(); code is generated by compiler 
		System.out.println("child class 0-org cons");
	}
	public static void main(String[] args) {
		new Child3();
		new Child3();  // during object creation 

	}
	}
 